### ISSUE TITLE
This library it doesn't work with Odoo 10

### ISSUE THREAD

**Issue by santiago1976** [timheap/jquery-xmlrpc#14]
jquery-3.2.1.js:3860 jQuery.Deferred exception: True is not defined ReferenceError: True is not defined
    at Object.<anonymous> (file:///C:/Users/user/Downloads/odoo-js/funciones.js:38:84)
    at mightThrow (file:///C:/Users/user/Downloads/odoo-js/jquery-3.2.1.js:3583:29)
    at process (file:///C:/Users/user/Downloads/odoo-js/jquery-3.2.1.js:3651:12) undefined

**Comment by ioterateam** [comment]
same with me, anyone know? 
url not found, error 404, I'm using php the url works fine

thanks
